### ISSUE TITLE
Most Recent Call Last

### ISSUE THREAD

**Issue by ColbyC** [clickthisnick/CraigLister#5]
```

root@debian:/home/python/Desktop# python craiglister.py
Traceback (most recent call last):
  File "craiglister.py", line 219, in <module>
    if (hasItBeenXDaysSinceFolderListed(dayListedFolder,3) == False):
  File "craiglister.py", line 188, in hasItBeenXDaysSinceFolderListed
    folderDate = datetime.date(int(dateSplit[2]) + 2000, int(dateSplit[0]), int(dateSplit[1]))
IndexError: list index out of range
```

**Comment by ColbyC** [comment]
I have received this error while testing code?

**Comment by derek-baker** [comment]
Looks like an 'off-by-one' error' that resulted from trying to access an element in an array that doesn't exist(the element doesn't exist). The script mostly worked for me last time I used it a couple of months ago. I DID have to modify my Gmail settings a bit though.
